### ISSUE TITLE
Definition of Done: Breakdown 

### ISSUE THREAD

**Issue by EduardSchwarzkopf** [Tweetmarked/Tweetmarked#1]
We need a DoD for a Breakdown. This means, how often do we need to breakdown a task from the backlog, till it is considered as done and can be pushed into the implementation column

AB#10

**Comment by skirianov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DoD](https://trello.com/c/lbfBa7JZ/1-dod)

**Comment by EduardSchwarzkopf** [comment]
simple test comment

**Comment by EduardSchwarzkopf** [comment]
Ok, here are some points that came to my mind:

- Is a single feature
- can be finished in about 1-3 days (invested time), less is ok
- can be done by a single dev

**Comment by skirianov** [comment]
-If feature requires multiple departments (backend / frontend / devops) then it should be broken down to different tasks and feature is completed only once all linked issues are resolved
