### ISSUE TITLE
Definition of Done: Implementation 

### ISSUE THREAD

**Issue by EduardSchwarzkopf** [Tweetmarked/Tweetmarked#2]
What are the requirements for an implementation to be considered done? 

AB#9

**Comment by EduardSchwarzkopf** [comment]
This definition will be used for frontend and backend implementation

**Comment by EduardSchwarzkopf** [comment]
So this is what i came up with after doing some research:

- Project builds without errors <- Are we going to have builds?
- Unit tests written and passed
- Feature tested and approved manually by dev
- Code is “non-breakable” (rollback is possible).
- [frontend] Design is mobile-first
- [frontend] Google accessibility check passed

**Comment by skirianov** [comment]
@EduardSchwarzkopf Yes, we will require some CI/CD split at least into a few categories:

- Frontend tests
- Backend tests
- DB tests

Rest I agree with your DoD

**Comment by EduardSchwarzkopf** [comment]
Alright, i will those into the backlog
