### ISSUE TITLE
Definition of Done: Review in Progess 

### ISSUE THREAD

**Issue by EduardSchwarzkopf** [Tweetmarked/Tweetmarked#3]
What should be the requirements for the review in progress to consider it as done?

AB#8

**Comment by EduardSchwarzkopf** [comment]
- 2 developers need to accept the pull request

**Comment by skirianov** [comment]
- Code aligned with style guide
- Code approved by at least 2 developers

**Comment by EduardSchwarzkopf** [comment]
Definitions added

> * Code aligned with style guide
>  * Code approved by at least 2 developers
